denote-link.el
denote.el

This fixes links in non org notes.

Fix links in non org notes

---

denote-faces.el
denote-link.el

Some adjustments:
- I used `$` for the end of the line.
- I used " " for the start of the filename in Dired (different for the backlinks buffer).

Adjust fontification

---

denote-dired.el

Pull request as discussed in #48.
I added the function in `denote-dired.el`. There is some code duplication between it and `denote-dired-rename-file`.

Add denote-dired-convert-file-to-denote

---

denote.el

Deduplicate keywords when read from stdin

Remove duplicate keywords

---

denote-faces.el
denote.el

Updated regex to allow fontification for non-ASCII characters

Regex to allow for non-ASCII characters in title and tags

---

README.org

Hi Prot -- this is just a small tweak to the readme to make it up to date with the current state of `consult-notes`. Great to see so much good development of denote!
- update info for consult-notes package
- add info about searching notes

Revise README for consult-notes & denote

---

denote.el

Unless the removed variables are useful outside of `denote.el`, I think they can be removed. Now, only `denote--prepate-note` and `denote-org-capture` set `denote-last-path`. I am not sure if `denote--prepare-note` really needs to set it though. I think it can be removed as well. What do you think?

Remove most denote-last-* variables

---

denote.el

Small cleanups. Check the individual commits.

Minor cleanups

---

denote.el

I don't intend to make other changes before 0.5.0.

Refactor denote--date

---

denote.el

This is a first step towards what we discussed in #85. I will try to remove the remaining key-regexp variables. I think I have an idea, but I will not be able to work on it tomorrow. This will let time to see if the current version contains bugs, but you can work on it if you want.

Remove some unused variables and functions

---

denote.el

Cleanups following discussion in #90. Check the individual commits.

Some cleanups for denote--only-note-p

---

denote.el

`denote--filetype-heuristics` should always return an md filetype if the
file extension is md even if no key regexps match in the file. In that
case, we use the first md type in `denote-file-types`.
markdown-yaml should appear before markdown-toml in `denote-file-types`
because it used to be the default markdown type of
denote--filetype-heuristics.

Fix denote--filetype-heuristics for md files when no key regexps match

---

denote.el

It is a common use-case to create a link in existing notes. In such cases, some text is already there, and user just want to create a link on that text (instead of inserting the link's title). With this change, if a region is active when user tries to insert a link, the region is replaced with the link while using the region's content as link's title.

Use region as link title when inserting a link

---

denote.el

Hi Prot,
It has been a while since my last contribution. I have just been using
Denote seamlessly. However, I kept having this issue. By default, when I
create a note, I use txt as the default format. Sometimes, I realize
that I actually wanted to use org. In this case, I just started over and
typed the title and keywords again. Other times, I have an old text note
which I want to convert to org to use Org's functionalities.
I have written a function (denote-change-file-type) to convert the file
extension and front matter to another format. This function only changes
the file extension and ADD a front matter at the beginning of the file,
retrieving the information from the old one. The old front matter stays
there. There are probably many other modifications to be made when
changing the …

Add function denote-change-file-type

---

denote-rename-buffer.el

Good job on `denote--file-with-temp-buffer`! I had noticed that unsaved
buffers where not renamed properly, but had not come up with a solution.
Some comments:
- `denote-rename-buffer` is added to `find-file-hook`. I think some
checks should be done early to determine if the renamed buffer can be
renamed (ie is a Denote note).
- Each specifier individually executes the
`denote-rename-buffer--common-checks` to retrieve the file and the
type.
- We can only check for `string-blank-p` in
`denote-rename-buffer--with-unique-name`. It already checks for
`string-empty-p`.
Some other general comments:
- The `or` condition in `denote--file-with-temp-buffer-1` does not seem
to make sense as it is. It seems to only consider `file-exists` in the
end.

Refactor denote-rename-buffer

---

denote.el

[Ready to be merged.]
Fix issue #209.

Fix issue #209

---

denote.el

Fix denote--trim-right-token-characters

---

denote.el

The built-in `denote-dired-rename-marked-files-with-keywords` function replaces all the keywords of marked files with user-input keywords. This is really useful, but my most common use-case is needing to add a particular keyword or remove a particular keyword from marked notes.
This commit re-arranges the plumbing of
`denote-dired-rename-marked-files-with-keywords` into two internal functions: `denote-dired-rename-marked-files--change-keywords` and `denote-keywords--combine`.
This lets us create two new functions --
`denote-dired-rename-marked-files-add-keywords` and `denote-dired-rename-marked-files-remove-keywords`.
Closes: #315

Create -add-keywords and -remove-keywords variants for denote-dired-rename-marked-files

---

denote.el

Use denote-extract-keywords-from path in renaming commands

---

denote.el

Also remove a small unnecessary check.

Minor cleanup in `denote-keywords--combine`

---

denote.el

Small issue when merging the latest pull requests

Use the new denote--file-type-org-extra-p in denote-link-dired-marked-notes

---

denote.el

This pull request fixes issues #274 and #299.
The current renaming functions are inconsistent. Some of them have
optional parameters `no-confirm` and `save-buffer`. Some have only one,
but it means both. Some have no optional parameters (but could have).
In this pull request, all renaming commands obey `denote-save-buffers`
(renamed from `denote-save-buffer-after-creation`) and
`denote-rename-confirmations` (see its docstring).
There are no user-visible changes, except that all optional parameters
have been removed in favor of obeying these two variables. Note that we
explicitly let-bind them ourselves in some commands, where it makes
sense.
The manual remains to be updated. Let me know how you want to proceed.
I can update it if you want.

Fix issues #274 and #299

---

denote.el

An internal simplification that makes the hash table of used-ids more transparent in the code.

Add denote--used-ids and simplify renaming commands

---

denote.el

Even though this is a big pull request, it does not contain much user-visible
changes. This is mostly all internal refactoring.
This pull request is the big one that streamlines all renaming commands. The
idea is to build all renaming commands (thus removing code duplication) on top
of 2 building blocks : `denote--rename-get-file-info-from-prompts-or-existing`
and `denote--rename-file`, similar in principle to `denote-rename-file-subr`
that we had at some point.
These 2 internal functions can be combined in various ways to get all the
renaming commands, as you can see in this pull request. All commands behave
exactly as before.
This is the user-visible changes:
- I replaced `denote-rename-add-signature` and `denote-rename-remove-signature`
with `denote-rename-file-signature` which can be …

Streamline the renaming commands

---

denote.el

This fixes issue #339, as discussed there.

Rework denote-file-prompt to work with relative paths in denote-file-history

---

denote.el

This is the `denote-use-*` variables we have been talking about.

Add denote-use-* variables

---

denote.el

Only fontify files that have an identifier

---

README.org
denote.el

See discussion in #383 for rationale.

Added a helper function to conditionally enable `denote-fontify-links-mode`

---

denote.el

The options `denote-save-buffers` (existing) and `denote-kill-buffers` (new)
now control what happens after a creation or a rename operation. Their default
is `nil`, meaning that we do not save or kill buffers automatically.
They should behave as expected. You can check their documentation. A few
notes:
- `denote-kill-buffers` is "stronger" in a sense than `denote-save-buffers`.
When set, it would not make sense to not save the buffer as well.
- We NEVER kill a buffer that was already visited before a rename operation. I
think this is an expected behavior. It would be strange otherwise.
- In issue #273, mentalisttraceur considered some other cases. For example,
another process could modify a file and our automatic killing of the buffer
could lead to data loss. I don't think that we need …

Option denote-kill-buffers to automatically kill buffers (issue #413 and #273)

---

denote-journal-extras.el

This function returns the path to a journal entry with the given date, or nil if there is none.
Refactored `denote-journal-extras-new-or-existing-entry' and `denote-journal-extras-link-or-create-entry' to use it.
Closes #442.

add `denote-journal-extra-path-to-new-or-existing-entry'

---

denote-rename-buffer.el

allow nil type in denote-rename-buffer--format

---

denote.el

I did not include the public functions in my last pull request!

Add missing public front matter retrieval functions

---

README.org
denote.el

See my comment in https://github.com/protesilaos/denote/issues/469#issuecomment-2453499835.

Link descriptions

---

denote.el

While resolving a merge conflict in my previous pull request, I accidentally reintroduced the bug in #510.

Reapply a fix that was undone in previous PR

---

denote.el

The last search features, I promise :)
This pull request implements the last few things `denote-search` has but Denote hasn't.
* A command for searching something in marked dired files (`denote-grep-marked-dired-files`). This allows great composability with `denote-dired`.
* A command for searching among files whose IDs are referenced in region (`denote-grep-files-referenced-in-region`). Specially useful for "See also" sections and the like, but it really is a versatile command.
I also implemented a display buffer action for both of them and `denote-grep`, which defaults to replacing current window.

Implement functions for searching in dired files and in a region

---

denote.el

This approach defines ‘denote-buffer-name-prefix’ as a customizable variable defaulting to "[D] ".
Then I define ‘denote-buffer-name’ as a function to wrap buffer names in such that they use ‘denote-buffer-name-prefix’. ‘denote-buffer-name’ also takes the opportunity to allow designating buffers as "special/temporary" or not which adds surrounding asterisks.
Lastly, I have wrapped all the Denote-related buffer names with ‘denote-buffer-name’ so commands like ‘denote-sort-dired’, ‘denote-backlinks’, and ‘denote-grep’ will all use ‘denote-buffer-name-prefix’.
BEFORE MERGING:
- Fix my placement of the definitions inside denote.el. I'm not sure what makes most sense to you.
- decide on a package-version for the introduction of ‘denote-buffer-name-prefix’. I have it set to "TODO" at the …

Implement ‘denote-buffer-name-prefix’ discussed as an aside in #595

---

denote.el

i.e. Just make the format string conditional, not the whole format.

De-duplicate code in ‘denote-format-buffer-name’
