protesilaos/denote

.gitignore
Hello,
I don't know if you would accept patches at GitHub PRs too. So I thought of trying that.
[I do have my copyrights assigned to FSF.]
=> chore: Ignore compiled and autoloads Emacs-Lisp files

denote-link.el
Fixes issue 10 over at the Github mirror:
<https://github.com/protesilaos/denote/issues/10>.
This regexp update now also matches the ID property. Refer issue 8 at
the Github mirror: <https://github.com/protesilaos/denote/issues/8>.
=> Identifier regexp improvements (support TOML and Org ID)

README.org, denote-link.el, denote-retrieve.el, denote.el
- Move `denote-use-org-id` from denote.el to `denote-link-use-org-id` in denote-link.el. The rationale for this change is that the ID property style will always work for Org files and doesn't need any customization; also that style doesn't add any org-id dependency.
- The org-id dependency is needed only if the user wants to access "active" feature of the "id:" type links like following and exporting.
Fixes https://github.com/protesilaos/denote/issues/8.
=> refactor: Default Org front-matter to use the ID property 

denote.el
Clicking on an id: link to a note in a subdirectory should work.
=> Set org-id-extra-files to all files in all subdirectories.

denote-dired.el, denote-retrieve.el
I was planning on opening an issue, but I was able to fix it.
Example:
```
#+title:        My Note (good)
```
The regexp captures `My Note (good` (without the `)`).
I could fix this by removing `\\b` from the regexp (but it breaks validation of double quotes around titles), but after reading Emacs manual on regexp, I still don't understand why it does not work with `\\b`. Also, the following similar examples give different results:
Example 1:
```
string: "good)%@"
regexp: "good.*\\b"
match: "good)%"        ;  "@" excluded
```
Example 2:
```
string: "good)&@"      ;  like Example1, but & instead of %
regexp: "good.*\\b"
match: "good"          ;  ")&@" excluded
```
I have tried to make it work by tweaking the regexp, but I was not successful. Then, I tried to rework the code a little and I …
=> When a note title ends with `)`, denote-retrieve--title-front-matter-regexp does not capture the `)`.

denote-dired.el, denote.el
I have been holding one last pull request until all other would be closed.
When I rename a note, it is often just to fix a typo in the title or change the wording. I rarely have to modify the whole title. This pull request just sets the `DEFAULT-VALUE` parameter of `read-string` in `denote--title-prompt` to the previous title instead of `nil` when using the command `denote-dired-rename-file`.
An empty input will just use the previous title. This would be useful if you just want to update the tags.
When prompted for a title, using `M-n` allows for editing of the previous title.
=> Set default-value to previous title in denote--title-prompt

denote.el
This is meant as a first step in supporting Denote with no keywords.
In various places, the `keywords` argument can be a single string or a list of strings. There are `stringp` checks and other conditions in various places of the code to handle this.
Now that we also want to support no keywords, I think it would be cleaner if `keywords` would always be a list of strings (at least internally in the code), whether it contains 0, 1 or multiple keywords.
This pull request just removes the previous conditions and checks. Proper support for the use case of no keywords would come later.
I have done some quick tests and it does not seem to have broken anything.
=> Clean keywords usage in order to support no keywords

denote-faces.el, denote.el
This pull request contains:
- Removal of `denote--keywords-in-files`. It was not doing much and it was only used by `denote--inferred-keywords` (which I have refactored a little).
- Refactor of `denote--extract` into `denote--extract-keywords-from-path`. Since we want to move away from a single big regexp, the function `denote--extract` would not be useful anymore.
- `denote--extract-keywords-from-path` is implemented using `string-match` while `denote--extract` was creating a temp buffer for the string and using `re-search-forward`. Any reason why it was implemented that way?
- Refactor of `denote--only-note-p` to remove the use of denote--file-only-note-regexp. Instead we can just check if the file name starts with an ID and ends with a Denote extension. Everything inbetween is …
=> More refactors to remove the big regexp

denote.el
We have had this discussion before, but the else part in the `if-let*` in `denote--file-name-relative-to-denote-directory` does not seem necessary. You mentioned that you had issues coming from `xref` without it. I find this strange, but I added `expand-file-name` just to be sure. That is the only thing I would imagine that could lead to the else part being executed. You should test your backlinks just to be sure!
=> Remove else part in denote--file-name-relative-to-denote-directory

denote.el
I was sure the function `denote-directory` was returning the expanded file name, but as reported in issue #43, it is not the case.
This pull request fixes that.
=> Expand file name of denote-directory

denote-link.el
This is an old minor bug.
I get this in `*Messages*` whenever the backlinks buffer is open:
```
Invalid face reference: unspecified [1331 times]
```
Nothing was broken though. This pull request removes the messages.
=> Specify existing face for backlink buttons.

denote-dired.el, denote-retrieve.el
> DEV NOTE 2022-07-16: proof of concept---help flesh it out.
Ok!
What would you say about these proposed functions (for more precision)?
```elisp
(defun denote-dired-rename-file-and-rewrite-front-matter (file title keywords) ...)
; Same as the old `denote-dired-rename-file`. I added it as an alias. We could also deprecate it.
(defun denote-dired-rename-file-and-add-front-matter (file title keywords) ...)
; Same as the old `denote-dired-convert-file-to-denote`
(defun denote-dired-rename-marked-files () ...)
; Same as your new `denote-dired-batch-rename`.
```
- In all of them, marked files are used.
- In my pull request, they are all implemented similarly. Since we specify that `denote-dired-rename-file-and-rewrite-front-matter` rewrites the front matter, it does not make sense to have it …
=> Renaming functions

denote-dired.el
I moved the check for `denote--only-note-p` in `denote-dired--add-front-matter`.
I added an `s` to `denote-dired-rename-marked-files-and-add-front-matters`. Does it make sense?
=> Renaming commands, minor adjustments

denote-org-capture.el, denote.el
`denote--prepare-note` is only used in 2 places: in `denote` and for org-capture. In `denote`, we let-bind `denote-file-type` and `denote-directory`. In this pull request, I remove the let-binding and pass the file-type and the directory directly to `denote--prepare-note`.
For org-capture, I noticed that the only thing `denote--prepare-note` was doing is set `denote-last-front-matter`.
---
`denote--id-exists-p` should also check the active buffers because a new note might not be saved yet.
---
I added 2 internals functions: `denote--get-all-used-ids` and `denote--find-first-available-id`. They are not used anywhere yet, but maybe they can be used to solve the collision issues.
---
I do not understand why we use `:no-check-current` in `denote--barf-duplicate-id`. Why is it needed?
=> Refactor denote--prepare-notes and other modifications

denote.el
Just a small cleanup of denote.el. There is no new code. You can look at the individual commits.
In summary:
- Put the convenience functions in their own sections.
- Rename the "denote command" to "denote command and its prompts" and move the helper functions out of it.
=> Cleanup of denote.el

denote-dired.el, denote-retrieve.el, denote.el
I have started some work following the discussion on the mailing list.
---
I moved some functions from `denote-dired.el` to `denote.el` for these reasons:
- Some are not related enough to Dired or specific to Dired.
- As a work-in-progress, it is not clear what we will end up with. We can split into more appropriate files later.
I have created a section for "Note modifications" in `denote.el` for these moved functions.
I have created 2 utility functions that will probably be useful soon:
- `denote--extract-keywords-from-front-matter`: The reverse of `denote--file-meta-keywords`.
- `denote--rename-file` that just renames the file without any prompts. Later, we can use it, for example, in functions like `denote-rename-file-using-front-matter`, `denote-rename-file-using-prompts` or …
=> Move functions from denote-dired.el and create some utility functions

denote.el
First step toward a more streamlined rename function.
In `denote--edit-front-matter-p`, I check that there is a front matter to edit. The rule is just that the note must have a "title" AND a "tags" line. This is the precondition for `denote--rewrite-front-matter` to be successful. If one of them is missing, we just add a front matter unconditionally and let the user do the manual adjustments. We can further refine this later.
Now that `denote-rename-file` modifies OR ADD a front matter, I made both `denote-dired-rename-file` and `denote-dired-rename-file-and-add-front-matter` obsolete.
I have to test this, but I wanted to share it.
=> Remove denote-dired-rename-file-and-add-front-matter

denote.el
When typing a title "my_title", I think it would be more natural to get "my-title" after sluggification than "mytitle".
This pull request makes this change. It also works for the keywords as well.
I fixed the docstring of `denote-allow-multi-word-keywords`. Previously, it stated that "word1+word2" would get converted to "word1-word2", but it is instead converted to "word1word2".
=> Replace underscore with hyphen in denote--slug-hyphenate

denote.el
This was wrong. `denote` was failing.
=> Fix denote--id-exists-p

denote.el
This is a proof-of-concept. I have some doubts, but I am sharing it with you.
I added a new section "File types" in the code. You can check the new **internal** variable `denote--file-types` and its docstring and other related functions.
It would still need refinements to be merged. We could then refactor many functions in denote.el to use the content of `denote--file-types`.
I copy here what I originally wrote for that pull request:
---
With `denote--file-types`, I did not consider user-friendliness. I just consolidated the various information we have about file types, without losing any of our existing functionalities. I suggest we first use `denote--file-types` internally for a while just to test how we like it and to allow us to make adjustments. We could disclose its existence to …
=> File types section

denote.el
I made some changes to denote--retrieve-filename-title to replace dashes with spaces and capitalise the link title for better typography when linking Denote attachments.
=> Update denote--retrieve-filename-title: remove dashes and capitalize

denote.el
As discussed in #95, this adds the option `denote-date-prompt-use-org-read-date`.
Note that `org-read-date`, when given no timestamp defaults to the current time, which would be good. However, the default seconds are always `00`. Defaulting to the current time for everything but the seconds is documented in their docstring. I have done nothing special to handle this better. This implies that a user who would create two notes within the same minute would have a conflicting identifier.
Given this, I am not sure if it would be better not to provide this option or to document this limitation.
Also, I did not load `org-read-date` conditionally to org being loaded because I did not know how to do it properly.
=> Add option denote-date-prompt-use-org-read-date

denote.el
Slight update to `denote--slug-hyphenate` to also remove leading dashes. Use case: file names wit tripple dashes when accidentally adding spaces at start of title/
=> Also remove leading dash when sluggifying title.

denote.el
- keywords should be allowed to be nil.
- The answer to yes-or-no-p should not yield the error "No marked files"
if the answer is no.
=> Fix denote-dired-rename-markd-files

denote.el
I am not sure of the right syntax when there are no keywords in an org file, but `::` looks strange. An empty string seems more appropriate, but I could not find documentation on this.
=> Return empty string when no keywords in org notes

denote.el
Hi Prot,
I have been using `denote-rename-file-using-front-matter` quite a bite and kept forgetting to save before evoking it so I added a prompt to the function for convenience.
P:)
=> Added a prompt to denote-rename-file-using-front-matter.

denote.el
If user has whitespace-only region active when inserting a denote-link, behave org-mode does when inserting a link in this case. i.e selected region is deleted, and an id-only link is inserted. Active region is trimmed regardless, so if user try to link "hello " part of "hello world", the text is changed to "helloworld" with "hello" being the link description and "world" plain text.
=> Org-mode-like insert-link behavior with empty active region

denote.el
Fixes https://github.com/protesilaos/denote/issues/111. Add a regular expression to exclude certain directories from denote-file-prompt. Useful for excluding temporary files when using a cloud-sync service.
This is my first Emacs Lisp contribution so please let me know if I'm missing anything obvious. I tried to emulate the existing style of `denote.el`.
Demo of the behavior:
https://user-images.githubusercontent.com/3778552/200026889-64940eef-c17c-430a-acfc-de0c0d25804a.mov
=> feat: Add denote-directory-exclusions

README.org
Denote started with management of thoughts/ideas in Emacs org-mode
and extends to files.  Some of the tools initiated by Karl Voit do
offer the addition of time stamps, key words from a controlled
vocabulary, etc on files (e.g., date2name) which may be processed
further (memacs).  It is worth to hint to them, as introduced by
this commit, in appreciation of an earlier invite.[1]
[1] https://github.com/protesilaos/denote/issues/117#issuecomment-1354372589
=> add crosslink to Karl Voit's work

denote-org-dblock.el
Hi Prot
Two minor updates for the dblock functionalities:
1. Add a `:reverse` option to the `denote-backlinks` dblock
2. Some minor clarifications in the use of sexp forms for the search input in the `denote-links` dblock
All the best
Elias
=> Minor updates for dblock

README.org
Hello Prot!
Hope you are well. Why perusing README of your denote package I noticed that the page under https://jao.io/blog/2022-06-19-simple-note-taking.html does not exist. This PR should fix that.
Best regards
Tomasz Hołubowicz
=> Fix broken link to jao's blog

denote.el
I'm on emacs 28.2 and I don't seem to have `seq-keep` available. This seems to work
=> Replace seq-keep with version-agnostic variant

denote.el
Hi, Prot! I watched your stream about denote and noticed that there are negated predicates which can be avoided by using the appropriate filtering functions.
=> Get rid of negated predicates

README.org, denote.el
Hi Prot,
I saw the changes about unique ids. I suggest this solution below. My
goal was to make ids robust everywhere, fast and without optional
parameters or options.
Affected functions:
- `denote`: Always creates a new unused id (see how below). No need to
barf anymore.
- `denote-org-capture-with-prompts`: Always creates a new unused id. No
need to barf anymore.
- `denote-barf-duplicate-id`: Obsolete as it is not used anymore.
- `denote-retrieve-or-create-file-identifier`: Removed. Use the
functions 'denote-retrieve-filename-identifier' (already exists) and
'denote-create-unique-file-identifier' (new).
- `denote-retrieve-filename-identifier`: New optional parameter
'no-error' to return nil instead of an error.
- `denote-create-unique-file-identifier`: New.
- `denote-change-file-type`: …
=> Duplicate ids

denote-journal-extras.el
There's probably better ways to write this function. Also, naming convention for variables might be off.
Thanks!
=> Use templates for creating journal entries

denote.el
I checked and removed the function `denote--default-dir-has-denote-prefix' as it does not seem necessary. I also simplified `denote--dir-in-denote-directory-p'. The returned value is not used.
=> Small cleanup

denote.el
I fixed `denote--buffer-file-names`. At first, this function was meant
to return buffers (including unsaved ones). At some point, I made it
check that the file was an actual (saved) file. This was not intended.
To fix this, I created a new function `denote-filename-is-note-p` that
does not check that the file is an actual file, but only checks that the
filename is a valid name for a Denote note. `denote--buffer-file-names`
should use this function instead. `denote--buffer-file-names` is used in
the detection of duplicate ids and in the function
`denote-link-dired-marked-notes`.
=> Add denote-filename-is-note-p and use it in denote--buffer-file-names

README.org
References the three articles in _Emacs Writing Studio_ that discuss Denote.
=> Added Emacs Writing Studio to publications about Denote

README.org, denote.el
Nothing major. I just refactored `denote-rename-file-using-front-matter` and I made `used-ids` parameter non optional in `denote-create-unique-filename-identifier`. This will force us to use `denote--get-all-used-ids` whenever we want to use it. In general, when we would use `denote-create-unique-filename-identifier` without `used-ids`, there was a risk that we would introduce some performance issues. Now, it will be more obvious if we do so.
I think it is all good for 2.1.0!
=> Small refactor

denote.el
This fixes #190.
I don't have a lot of experience in Elisp, so this might not be the best way of doing it, feel free to change things. Basically, I take the current path and build up a list of all sub-paths in it (e.g., for `"/home/docs/stuff/"`, we get `'("/home/" "/home/docs/" "/home/docs/stuff/")`. As long as one of them is a member of `denote-dired-directories`, we should enable `denote-dired-mode`. This way, we don't have to actually scan for subdirectories.
=> Allow checking for subdirs of `denote-dired-directories' (fix #190)

README.org, denote-journal-extras.el, denote-org-dblock.el, denote.el
I have refactored `denote-directory-files` to make it do the job of `denote-all-files`, `denote-directory-files-matching-regexp` and `denote-directory-text-only-files`. I deprecated these functions, but kept them for now because some people might have started to use them.
This is just a suggestion. I don't think it is bad that we have separate functions, but if you think this is a good change, it is ready to be merged.
=> Refactor denote-directory-files and deprecate functions

denote.el
Four file renaming commands may lose spaces (denoted by the "=" in existing filenames) when the user renames the file:
1. denote-rename-file
2. denote-dired-rename-files
3. denote-dired-rename-marked-files-with-keywords
4. denote-rename-file-using-front-matter
This is caused by the function `denote-sluggify-signature`, which calls (indirectly) `denote--slug-no-punct`, which removes, among many other characters, all "="s, which represent spaces.  These spaces are thus lost even if the user does not change the signature.
To remedy this situation, all "="s are turned into spaces before being sent to `denote--slug-no-punct`, as spaces are not removed by this function.  The function `denote--slug-put-equals` turns these spaces into "="s at the end of the file-renaming operation.
=> Fix to signature losing "="s when file is renamed.

README.org, denote-journal-extras.el, denote-silo-extras.el, denote.el, tests/denote-test.el
[Ready to be merged.]
Ignore this pull request if I have missed some use-case.
I have looked in the manual because I wanted to understand
`denote-user-enforced-denote-directory`. It seems like users are meant
to let-bind it to enforce a specific value for `denote-directory`.
However, after some tests, let-binding `denote-directory` directly also
works.
I have removed this user-option in this pull request and adapted the
manual accordingly.
=> Remove denote-user-enforced-denote-directory

README.org, denote.el, tests/denote-test.el
[Ready to be merged.]
Hello Prot!
Recently, you have made a change in `denote-rename-file` to have the
keywords prompt displays the existing keywords. This is good!
There are still some inconsistencies when we explicitely choose to input
nothing (empty string).
For example, given the note
"20231223T111111==aa--test__keyword1_keyword2.txt", if I input nothing
for all prompts, the title and signature are removed, but the keywords
stay. Also, when called from lisp, passing nil or empty string to title
(or signature) yield different results, contrary to what the
documentation says.
I think that now that we display the default value for all prompts
(including keywords), we can obey the prompts (and remove the component
from the file if the input is empty).
This pull request makes …
=> Fix `denote-rename-file` when called with empty inputs

README.org, denote.el, tests/denote-test.el
[Wait after pull request #208 is merged.]
Hello Prot!
Do not merge this pull request yet. I will rebase it on main when the
other one is merged.
Sorry about the recent (big) pull requests I have made recently. Please
take all the time you need and don't feel pressured.
--------
In this pull request, I have polished the denote-sluggify-* functions,
as well as the `denote-letter-case' function and related. I have made
them work in a more general and unified way. This allows more
flexibility to the file names.
I have replaced `denote-file-name-letter-casing` with
`denote-file-name-slug-functions`. The idea is the same, but the user
can define any function instead of just verbatim and downcase. The
default behavior does not change. Note that I have made it a `defvar`
just because I do not …
=> Slug functions

README.org, denote.el, tests/denote-test.el
[Wait after pull request #208 is merged.]
I have moved the sorting of keywords outside `denote-keywords-prompt`
for these reasons:
- While investigating the error fixed by commit e2ba6c1, I discovered
that if we set a transient for the `denote` command and call it
through the transient, then we get the interactive behavior (prompts),
but `call-interactively-p` seems to return nil anyway. This makes me
think that we should try to avoid this function. Fortunately, it was
not necessary to keep it in our case.
- When calling `denote-rename-file` from lisp, the keywords are not
sorted. This is not coherent with the `denote` command, which always
sorts keywords. This is fixed. `denote-add-front-matter` is also
fixed.
- Double sorting was happening in the case of `denote-region`. Not an
issue, …
=> Do not use call-interactively-p and make renaming commands obey denote-sort-keywords

README.org, denote.el, tests/denote-test.el
Hello Prot!
Even if there are still a few pull requests pending, I am moving forward
with the ideas I have for Denote. Don't feel pressured. The diff of this
PR includes the previous ones (so this one looks big), but it is
actually a small one. I decided to keep them sequential in terms of
commits so that they are easy for you to merge in order when you are
ready. I can always rearrange them if you prefer them in another order.
You can check the individual commits.
-------
I was able to make `denote-region` obey `denote-prompts`. The issue I
had was that both `denote-region` and `denote` tried to use the region
internally, so there was some conflict when I tried to call `denote`
from `denote-region`.
The solution was simple. I just added the variable …
=> Make denote-region obey denote-prompts

README.org, denote-journal-extras.el, denote-silo-extras.el, denote.el, tests/denote-test.el
As reported in #218, removing the user option
`denote-user-enforced-denote-directory` has created a regression. I did
not know that we could set `denote-directory` to `default-directory` in
this way. I now understand why this user option was added in the first
place.
I have done some testing and I am having issues with both the old and
the new code. So I just reverted commits 5e9b6b3 and 49a0608 for now.
I will do more experimentation and might come up with something later.
Sorry about that!
=> Revert changes about denote-user-enforced-denote-directory

denote.el
I have added the function `denote--command-with-features` which is
intended to replace `denote--command-with-default-title` and
`denote--link-after-creating-subr` and other other ways to call
`denote`. This allows to compose them together.
I have also added the variable `denote-save-buffer-after-creation` (not a
user option for now).
I have also replaced `denote--use-region-in-denote-command` with
`denote-ignore-region-in-denote-command`.
This is not used for now in the rest of the code, but I will do the
refactoring later.
Ready to be merged!
=> Add denote--command-with-features and denote-save-buffer-after-creation

denote.el
I have added the user option `denote-link-description-function` (as a
defvar for now) which defaults to display the signature (if present) and
the title. I think it is a good default, but we can change it. It is now
easy to configure the link descriptions to look like:
- "Link"
- "20240101T111111--My-note.org"
- "My file title"
- "My file title (keyword1, keyword2)"
- "sig1z3   My other title"  (the default if signature is present)
- "My other title (sig1z3)"
- A prompt for the description
- etc.
`denote-link-description-function` can be `let` bound if we want to fix
the description format in specific functions, but we should avoid doing
that and let the user decide most of the time. The user can also let
bind this variable if he wants to change the behavior for a specific
command.
Some …
=> New variable `denote-link-description-function` and some bug fixes

denote.el
[Pull requests ready to be merged in this order: #221,#222,#223.]
Just a small pull request to enforce that no consecutive -,_ or = are
present in file names, even if the user does not do any sluggification
through `denote-file-name-slug-functions`. Also, single underscores are
removed in keywords as well.
=> Always remove consecutives -,_ or = from file names

denote.el
Just a small pull request to remove dot characters automatically in file
name components, even if this is not done by
`denote-file-name-slug-functions`. Also =, - and _ should be removed at
the **end** of the file name component.
I think file names are robust now.
=> Enforce other rules in the file name

README.org, denote.el
In the docstring of `denote-link`, it was said that an empty region
leads to links of type `id-only`. I forgot to make this work also in the
new code. This commit fixes that. Note that this works because the
default `denote-link-description-with-signature-and-title` decides to
return an empty string when given an empty region. This can behave
differently if the option is set to another function, which is ok.
=> Fix denote-link-description-with-signature-and-title

README.org, denote-org-extras.el, denote.el
Fixes:
- Fix `denote-org-extras-dblock--get-file-contents`, as reported in
#224.
- Make `denote--keyword-history` an alias of `denote-keyword-history.
- Fix issue #230.
- Update some docstrings and README.org about link descriptions.
=> Various fixes

denote.el
=> Linking functions can be used in files outside denote-directory

denote.el
Remove `denote--command-with-default-title` and use `denote--command-with-features` instead.
Also, there is a bug in `denote-find-link` when called from a note in a subdirectory.
=> Cleanup and bug fix

denote-org-extras.el
This property is automatically added to a task when we mark it as DONE. If both DATE as well as CREATED are not available, this is a valuable property to use when determining the date of the new note.
=> Fix: Consider the CLOSED property of the org-heading for heading-date

denote-org-extras.el
This requirement might be specific to my workflow and I would love maintainer feedback about it.
1. denote-subdirectory-prompt: When I am extracting data from my org-files as Denote notes, I _almost never_ want them to end up in the default directory. Instead, I want them to go to different directories based on the kind of content I am extracting.
2. denote-signature-prompt: I use signatures to track trails of thought, and as such I use them for certain kinds of notes. I'd like this data to be converted properly to Denote when I move from subtree-based notes to Denote notes.
=> Use denote-prompts to prompt user when extracting org subtree

README.org
- Corrected variable name from `user-enforced-denote-directory` to `denote-user-enforced-denote-directory`.
- Removed the paragraph that referred to its usage in `denote-org-extras-extract-org-subtree` function. Apparently, this function does not use `denote-user-enforced-denote-directory` variable.
=> Fix typo in variable name in documentation

denote.el
This commit modifies the following functions:
- `denote-type`
- `denote-date`
- `denote-subdirectory`
- `denote-template`
- `denote-signature`
Instead of overwriting the value of `denote-prompts`, this change adds the specific symbol to the existing value of `denote-prompts`.
=> Update denote-create-* commands to respect `denote-prompts`

denote.el
Hi! As suggested in #251, I implemented the change to `denote-link-return-links`. 
With this change, `denote-link-return-links` will avoid keeping visited buffers open.
=> Kill "hidden" buffer generated by `denote-link-return-links`

denote.el
Hi,
when using `denote-org-extras-extract-org-subtree` I found that `id` and `date` of the extracted note are always with current date (but `DATE` or `CREATED` properties were present in the original heading).
The rootcause is probably typo in the condition at the end of `denote-parse-date`.
=> Fix condition in denote-parse-date 

denote-org-extras.el
To reproduce the problem: open a new note and while it is empty, try to insert and populate an org dblock of type "denote-missing-links".
This leads to the following stack-trace:
```
Debugger entered--Lisp error: (wrong-type-argument stringp 65)
file-name-nondirectory(65)
file-name-extension(65 :period)
denote-get-file-extension(65)
denote-get-file-extension-sans-encryption(65)
denote-filetype-heuristics(65)
denote-link-description-with-signature-and-title(65 nil)
denote--link-get-description(65)
#f(compiled-function (file) #<bytecode -0x3aa12408d80ef11>)(65)
mapc(#f(compiled-function (file) #<bytecode -0x3aa12408d80ef11>) "All links matching ‘reference/2024012’ are present")
denote-link--prepare-links("All links matching ‘reference/2024012’ are present" org nil :no-other-sorting) …
```
=> Fix edge-cases when inserting missing links via org-dblock

README.org, denote.el
I have checked the documentation you made about
`denote-link-description-function`. There is a difference between what
is documented and the implementation. The current code requires that
`denote-link-description-function` be a function that takes two
parameters instead of only one. However, what you have documented is
better than what is implemented.
In this pull request, I removed this second parameter. It really is
unnecessary and may be confusing.
Since the functionality has not been released in an official version, it
does not seem to late to fix it.
=> Make denote-link-description-function require a function with only one argument

denote-rename-buffer.el
The fix for #261 did not work for keywords, as `denote-retrieve-front-matter-keywords-value-as-string` returns an empty string when no keyword is found, which is considered as satisfying the `cond`. I propose instead to get the list of keywords using `denote-retrieve-front-matter-keywords-value`, combine them if non-empty, otherwise get the keywords from the file name.
=> rename-buffer: really retrieve keywords for non-text files

denote.el
`denote--retrieve-title-or-filename` is used in the `denote-explore` package.
=> Make denote--retrieve-title-or-filename public

README.org, denote.el
In this pull request, I have done the following:
- Revert commit 232bd90 because of what is explained in #292.
- Make `denote-dired-rename-files` also obey the *order* of elements in
`denote-prompts`.
I have also simplified a `:safe` declaration, since `nil` is a list (the empty list).
=> Renaming commands

README.org, denote.el, tests/denote-test.el
Hello Prot,
I suggest that we remove `denote-file-name-deslug-function` from the
upcoming version 2.3.0 because it will be new in this version and
it is actually not very useful.
First, desluggification of keywords and signature is never used in the
code base, so this part is totally useless. As for the title
desluggification, it is only used in
`denote-retrieve-title-or-filename`. This is used in renaming commands
to provide a suggested title and for the link descriptions. This only
applies when we cannot find the title from the front-matter and there is
a title in the file name. I think the raw title (not desluggified) is
not a bad suggestion/description in those cases. The desluggified
suggestion may not be useful enough to warrant a user option.
Ignore this pull request if you think …
=> Remove denote-desluggify

denote.el
When removing modules, we removed `project.el` integration at the same
time. This caused an issue with backlinks because xref can use relative
file names (relative to the current project).
However, it is better to have xref retrieve its results in absolute form
and then arrange the results to relative form ourselves because,
eventually, notes will not be all under the same directory/project.
I have thus removed `project.el` integration again and fixed the code to
still use relative paths. I am unsure why we added `denote-project-find`
to `project-find-functions` hook for backlinks buffer. I suspect it was
to support relative paths somehow. I have removed it and tested the
backlinks buffers and they work as intended.
This is ready to be merged. It can be part of 2.3.0 as you have already …
=> Actually... remove `project.el` integration again

denote.el
#298 affected all renaming commands : `denote-link-or-create`, `denote-link-after-creating`, `denote-link-with-signature`, `denote-link-after-creating-with-command`.
`denote-add-links` was not affected, but it benefits from this check as well. It was crashing when used on a non-supported buffer.
=> Fix error message for all linking commands in Org capture buffers

README.org
Fix a doc typo in section 3.1.5 The denote-save-buffer-after-creation option
=> fix a minor typo in section 3.1.5 in README.org

denote.el
It was not doing much more than `denote-format-file-name`.
=> Remove denote--path

denote.el
Maybe someone has set `denote-files-types` to nil because he only uses the file name scheme of Denote.
I issue an error in `denote--valid-type` instead of failing later.
=> Issue error in denote--valid-file-type if denote-file-types is nil

denote.el
- rename `denote--file-type-org-capture-p` into `denote--file-type-org-extra-p`
- add case for an `*Org Note*` buffer
=> Extend org file type detection

README.org, denote.el, tests/denote-test.el
Consider removing `denote-convert-keywords-to-crm`. We never use it because it always makes more sense to work with keywords as a list. It is better to use `denote-extract-keywords-from-path`.
We can also remove `denote-retrieve-front-matter-keywords-value-as-string` for similar reasons.
Let me know if you think it is necessary to make them obsolete for now instead or if you would like to keep one or both of the functions. I think it is better to encourage the manipulation of keywords as a list and we already have suitable functions for that.
=> Remove unused functions

denote.el
Two commits. Nothing major or breaking.
- Use `denote-retrieve-front-matter-title-value` instead of an alias
- Use `denote-retrieve-filename-identifier` and compare id with `string=` instead of `string-prefix-p`. This is more general and will be ready for when file name components are in a different order.
=> Refactorings

denote.el
A pull request to fix issue #271. Has no impact on users that keep the default sluggification. Those that don't are allowed to have consecutive hyphens in titles. We do not remove them.
The fontification does not need to be updated. It handles this correctly already.
=> Fix issue #271 (Allow -- in titles)

denote.el
As commented in #333, in this pull request:
- Do not ask to modify front matter if not applicable (ie if only the
signature is changed).
- Renaming commands should focus on renaming the file name components
(not the extension or file type) for the reasons given in #333. Thus,
I have reverted some of the changes I made in #333 (the new
parameters).
=> Revert some changes in #333 and do not prompt for front matter if only signature is modified

README.org, denote.el
As explained in issue #339, I kept the `no-require-match`, but changed it back to using a single function.
=> Make denote-file-prompt return an absolute path

README.org, denote.el
I propose that `denote-rename-file` and related do not prompt if we are
editing a file and directly use the current file as the target of the renaming
right away for a better user experience and also to complete the solution of
#279 (allow renaming new notes that have not yet been saved). We already avoid
this prompting when we are in Dired. I think maybe it was also the original
intention: prompt only as a fallback.
What do you think?
If we want, we could provide documentation to get the old behavior back in the
manual, though I would not see why someone would want to call
`denote-rename-file` out of context in a random location that is not a file.
=> Make renaming commands rename the current file without prompt

denote.el
In this PR, I have addressed your comment in my previous PR and introduced a
few more cleanups.
The changes will help with resolving #279 to allow renaming new notes that are still
unsaved.
I also added checks to creation and renaming commands to avoid creating a note
if the file already exists. This is not a concern for now because the id is
unique and part of the file name, but we may want to make it optional
eventually.
Just a comment regarding your last commit: The change is not only stylistic:
`re-search-forward` behave differently whether `NOERROR` is `t` or any other
non-nil value such as `:no-error`. Check its docstring. I have discovered this
myself as well while working on the upcoming new fontification. Same thing
with `completing-read`: `t` and `:require-match` do not have the …
=> Other fixes

denote.el
I made this pull request to fix my mistake as reported in #357. Sorry about this!
I may add another commit soon. I feel like there is something awkward with the
way we handle the title and the renaming convenience commands. For example,
`denote-rename-file-signature` called on a file that is not yet a Denote file.
This is a case I may not have considered in my refactoring.
Anyway, don't wait to merge this current pull request.
resolves #357
=> Fix issue on note creation caused by commit bce7778

denote.el
This is a proposition for a new fontification. It works with our current file
names, but it also supports the future file names that can have permuted file
name components. It works in Dired and the backlinks buffer.
For now, titles always need to be prefixed with their delimiter (`--`) even if
they are the first component. I prefer keeping options open for now.
Also the code for the various matchers are all similar. I prefered keeping
them separate for now, even if it meant some code duplication.
You can give it a try!
Whenever we are ready and satisfied with the result, we can merge it, even if
we don't have the code for the permutation of file name components yet.
Here is an image of the results:
=> Rework the fontification

denote.el
This is a small pull request, but the whole feature is there!
I made `denote-file-name-components-order` a defvar because I do not know how to make it a defcustom. All file name components must be present.
This closes #332. (The delimiter of identifiers is @@.)
=> Add `denote-file-name-components-order` to allow reordering

denote.el
Bug fixes:
- This fixes the fontification. If we have issues with that in the future, we
can also replace `denote-faces-dired-file-name-matcher` with the function
[`dired-filename-search-forward`](https://github.com/protesilaos/denote/issues/271#issuecomment-2113961191) that mentalisttraceur shared in #271.
I tested it as well and it worked. Just mentioning it as a possible alternative.
- I also found another unrelated bug: `denote-org-capture` would always use
the current time for the id in the front matter irrespective of the value of
a possible date prompt.
I added some safeguards for when we will allow identifiers to have other
formats. The code is useless for now, but it is ready.
- I made the fontification ready to handle any identifier format.
- Prevent infinite loops in case …
=> Bug fixes: Fix the fontification + another bug

denote.el
Follow on from #344 
This addresses one issue that @protesilaos raised about disabling `denote-fontify-links-mode` and invisible text being left behind.
PS: I thought that removing the font-lock keyword would reset the text properties, turns out that is only true for `face` properties. I don't know how org addresses this issue yet, but this PR is one potential fix.
=> Add an invisibility spec to address disabling `denote-fontify-links-mode`

denote-journal-extras.el
The `denote-journal-extras--entry-today` was misbehaving if keywords were in front of the identifier (which is allowed since denote 3.0.0). The corrected version (1) searches for files only based on date and (2) subsequently filters them for the denote-journal-extras-keyword.
=> denote-journal-extras--entry-today & custom filename component order

README.org, denote-rename-buffer.el, denote.el
Hello Prot, thanks for all the work you've done with Denote!
Something I've wanted is some kind of indicator in the mode line that would alert me to the presence of backlinks to a file that I might want to investigate. I've put together a little prototype. It's clumsy; I hope you can give me some pointers on how to improve it. Here is what it does:
It adds `%b` to `denote-rename-buffer-format` which `denote-rename-buffer--format` will replace with `denote-buffer-has-backlinks-string` (defaults to `→ `) when the buffer has backlinks pointing to it.
The way it checks if a buffer has backlinks is possible more expensive than necessary; I call `(length (denote-link-return-backlinks file))` and check if the result is non-zero; that way I know for sure if a buffer has any backlinks Denote would …
=> Add indicator for buffer having backlinks to denote-rename-buffer

denote.el
Adds support for using templates that dynamically generate content using a function.
Fixes #394
=> Support functions in `denote-templates`

denote.el
Just adding support for function templates in `denote-org-capture` following the last merged pull request.
=> Add support for function templates in denote-org-capture

denote.el
I think you mixed two things in commits 7f9d040 followed by 8701908. You removed a line `(setq-local default-directory ...)` and added a line `(setq-local denote-directory ...)`. Those 2 are unrelated and removing the first line causes issue #412.
In the end, it is a good thing that this line is removed though. It was probably there because we open buttons in backlinks buffers by calling `find-find` on the relative path. But we should try to always work with absolute paths in the code.
To fix #412, I made `denote-link--backlink-find-file` work with absolute paths instead of reintroducing the `(setq-local default-directory ...)` line. It is ready to be merged.
=> Use absolute file path in denote-link--backlink-find-file

denote.el
I have reworked `denote-link-return-links` to limit the use of `with-temp-buffer` to get what we need.
You will notice that I reverted your last change to `denote-link-return-links` because you added a new parameter to `denote-link--expand-identifiers`, but it is used in `denote-org-extras.el`. It must have broken something there. I have kept `denote-link--expand-identifiers` because it is used there, but maybe we can use `denote-link-return-links` instead and remove it.
`denote-link-return-links` should also be more efficient now. Previously, for each notes we looped through all links in the file.
This is ready to be merged. I will get to `denote-link--prepare-backlinks` tomorrow.
=> Rework denote-link-return-links (fix issue #416)

README.org, denote.el
This does not affect the interactive `denote-rename-file`.
When called from lisp, one may believe that `(denote-rename-file
"some-file.org" "new-title")` will only rename the title. However, it also removes keywords and signature.
It may be confusing (see for example #405) to have them optional. I think it is better to make them mandatory for this reason.
=> Make denote-rename-file parameters non-optional

README.org, denote.el, tests/denote-test.el
This pull request just cleans up the default sluggification before exposing it
to users. The behavior is unchanged.
Here are the changes:
- Remove `denote-excluded-punctuation-regexp`. It was a `defconst`, so users
could not modify it anyway. It also ended up being used "as-is" only for the
title sluggification. We worked around it in both the signature and keyword
sluggification. So it was not very useful in the end.
- Deprecate `denote-excluded-punctuation-extra-regexp`. Users should customize
`denote-file-name-slug-functions`. It should be easy now just looking at the
default sluggification.
- Removed the extra-characters parameter from `denote--slug-no-punct`. It was
one of the workaround mentionned in the point above to have signatures
remove hyphens as well.
The character regexp is …
=> Clean sluggification functions

denote.el
In this pull request, I just extracted the ***function*** `denote-file-type` (not to
be confused with the ***variable***) from `denote-filetype-heuristics` as
suggested in #284.
There may be value in having this function that just retrieves the file type
of a note, without the extra checking that `denote-filetype-heuristics` does
for special org buffers.
I believe that even our code should use the `denote-file-type` function
instead of `denote-filetype-heuristics` in a few places, but I have not
changed anything about that here. This can be done later, if needed.
You may want to credit mentalisttraceur for this change in the release
notes. See #284.
This also closes #284.
=> Add denote-file-type function

denote.el
This fixes the issue that I could reproduce in #439.
=> Use file-truename to handle symbolic links (issue #439)

denote-journal-extras.el
When using this function, I always created a journal file if it was missing. As this simplifies the other functions that uses it as well, I propose to have `denote-journal-extra-path-to-new-or-existing-entry` create a journal entry if it is missing.
=> make denote-journal-extra-path-to-new-or-existing-entry create a missing entry

README.org, denote.el
This should fix the issue reported by ssl19 in #435 about digits being sluggified in keywords.
The hyphen character should appear last in a character alternative.
=> Fix issue reported in #435

denote.el
This pull request removes the redundant "Denote" item from the `denote--menu-contents` variable. 
This item surprisingly does not do anything when clicked, so all the more reason for it to be removed.
=> Remove redundant "Denote" item from denote--menu-contents

denote-org-extras.el, denote.el
I noticed some warnings pop up during a reinstallation of Denote and went and fixed them.
Here are the errors for reference:
```
⛔ Warning (comp): denote.el:4347:15: Warning: variable ‘_’ not left unused
⛔ Warning (comp): denote-org-extras.el:640:15: Warning: variable ‘_’ not left unused
⛔ Warning (comp): denote-org-extras.el:637:15: Warning: variable ‘_’ not left unused
```
Unlike `pcase` which holds a special meaning for `_`, there's no way to mark a let-bound variable as ignored but we can omit the SYMBOL name from the VARLIST and the `when-let` expression will still evaluate correctly.
=> Fix unused let-bound variable warnings

denote.el
I removed the nil checking of `denote--dir-in-denote-directory-p`. It is not
needed. It is an internal function. Calling it with nil would be a mistake. It
seems like it came from one of my commits (34daa52) where we were using a
`when-let`. It does not look like it was introduced to fix a bug. If there is,
we should ensure that we call it with a non-nil value.
I removed the condition in `denote-link--map-over-notes`. If one open the
parent of denote-directory in Dired and use "i" on the denote-directory, the
notes of this subdirectory will be listed in the current Dired buffer. The
user can mark them and call denote-link-dired-marked-notes. Previously, this
would fail because the current Dired buffer is not in denote-directory.
Speaking of `denote-link-dired-marked-notes`, since commit …
=> Some cleanup and fix `denote-link-dired-marked-notes`

denote.el
Sorry about this regression. I tested `denote-link-dired-marked-notes`, but not `denote`. I sat on these changes for some time and thought I had checked all locations of `denote--dir-in-denote-directory-p` already. I must have confused it with something else.
=> Fix regression caused by commit 4db0214

denote.el, tests/denote-test.el
In response to #467 and to allow us to handle the front matter in future development, I have added the missing front matter retrieval functions in `denote-file-types`. I assumed the signature would be included eventually.
Since we still do not use them, this should not break anything. I created and renamed a note of each type to be sure.
Note that I renamed `:date-format-function` to `:date-value-function` to be consistent with the other components.
=> Add remaining front matter retrieval functions

README.org, denote-journal-extras.el, denote.el, tests/denote-test.el
This pull request is mostly about date handling, but there are a few other
cleanups as well.
- `denote-get-identifier`: The `date` parameter is no longer optional. This a
a function (not a command) and we only used it without a date once. Also, it
does not check `denote-valid-date-p` anymore. Within the scope of
`denote-get-identifier`, it is too late for this validation. The callers
should have done this. We almost always did this already. I patched the only
place where we did not.
- `denote-valid-date-p`: Unchanged. This is the function that returns a valid
date object (or nil). It is good!
- `denote--date`: Renamed to `denote--format-front-matter-date`.
- `denote-parse-date`: Obsoleted. It was just like `denote-valid-date-p`, but
it converted nil dates to `(current-time)`. I think this …
=> Cleanup of date handling function and more

denote.el
I moved code from `denote--rename-get-file-info-from-prompts-or-existing` back to `denote--rename-file` because it would cause issues when `denote-rename-file` is used from lisp.
When calling `denote-rename-file` from lisp with a nil date, it would remove the date, ignoring `denote-generate-identifier-automatically`. Also, using keep-current in `denote-rename-file` would remove the date.
=> Fix denote-rename-file when called from lisp

README.org, denote.el
This new `denote-rewrite-front-matter` handles all front matter
lines/components. It works on each of them individually. If a line has no
value, it is removed. Removed lines are added again automatically on rename,
in a good position, if they have a non-empty value.
The new `denote-always-include-all-front-matter-lines` controls whether all
lines are present, even if the corresponding value is empty. I made the
default be `t` because that is currently what we are doing for keywords (ie
there is a keywords line even when there is no keywords).
------
This is a big pull request, so you may want to experiment with it before
merging it. You can try removing and reordering lines in a note and in the
front matter template and call something like this:
```
(denote-rewrite-front-matter …
```
=> Refactored `denote-rewrite-front-matter`

denote.el
I added the signature in the front matter. I think we should keep
`denote-always-include-all-front-matter-lines` to `t` because it is the
current behavior for the keywords line when there are none. It is also less
surprising to users if they get a new signature line than if they have a
keywords line disappear. Users have these options:
- Set `denote-always-include-all-front-matter-lines` to `nil`.
- Remove the signature line from their front matter template.
The new convenience `denote-rename-file-date` allows changing the date/id, as
long as we find no links to the note. A user-error is thrown otherwise. I
think it is better to throw a user-error instead of ignoring silently. When
renaming multiple files in a single operation, it may be an inconvenience, but
it is probably not a good …
=> Signatures in front matter, change id/date and bug fix

denote-journal-extras.el
I just saw a compilation warning about this being an obsolete alias.
=> fix obsolete alias

denote.el
In this pull request:
- `denote-front-matter-components-present-even-if-empty-value`
defaulting to `'(title keywords date identifier)`. The signature is
not included so things should keep working as before for users.
- Fixed smalls issues in `denote--get-file-components-for-rewrite` and
`denote-rewrite-front-matter`.
- Moved the backlinks check in `denote--rename-file`.
- Refactored `denote-rename-file-using-front-matter`. It was not
handling all front matter components. Though it was a general issue,
I think you noticed it when trying to integrate `markdown-obsidian`.
It should work now. Check its docstring!
------
I have seen your obsidian branch. I have two small comments:
1- The `denote-*-key-regexp` should not be empty strings for the
missing components, or else it will match. The …
=> Small fixes, `denote-rename-file-using-front-matter` and signature line only when there is a value

denote-org-extras.el
The Org dynamic block defining function mentioned the wrong function to create the block. A simple mistake that is now corrected.
=> fix org dblock definition of missing-links

denote.el
This is not a new issue, but `denote-retrieve-title-or-filename` has 2
issues:
- It validates that the file is in `denote-directory`.
- It checks whether the file has an identifier.
This leads to the following consequences:
- The front matter title can become sluggified on rename if the
location of the file is not in `denote-directory`. This can also
happen when symbolic links are involved (see issue #439).
- The same issue can happen with notes that do not have an identifier.
I have reworked `denote-retrieve-title-or-filename` so that it does
not check the location of the file (there is no need for this) and
also to be smarter in validating that the note has a denoted filename
(instead of just looking for the presence of an identifier).
If you want to review the history of your changes …
=> Fix denote-retrieve-title-or-filename and other tweak

README.org, denote.el, tests/denote-test.el
In this pull request:
- I have made adjustments to the recent code about `initial-date`. It
was not working with `denote-generate-identifier-automatically` and
notes without identifiers.
- In a recent pull request (#476), I reworked the internal date
handling functions so that we always only have to work with dates
that are represented as date objects (or nil for "no date"). I think
it makes sense to keep this consistent throughout the code. With
that in mind, `denote--date-convert` can benefit from this
simplification, as it is an internal function.
- `denote-date-prompt` now accepts an `initial-date` parameter. The
docstring says that the type of this parameter should depend on the
value of `denote-date-prompt-use-org-read-date`. This is not really
true, as the current code will work …
=> Small adjustments for notes without identifier

denote.el
For issue #500. See discussion there.
=> Make renaming commands work in denote-org-capture

denote.el
In this pull request:
- Fixed issue #513.
- `denote-file-has-denoted-filename-p` does not validate the presence of an identifier. So we also have to check that `denote-file-has-identifier-p` in `denote-link--map-over-notes` because linking requires identifiers.
I wanted to include other small changes. For example, handle the `keep-current` parameter in `denote--rename-file` instead of its current location, but I did not have time. I will do it later.
=> Some fixes

denote-sequence.el
As pointed out in #516, the `sort` function seems to have a mismatching paradigm depending on the Emacs version the code is run on. However, the `denote-sequence--get-largest` implementation was simply using the `:in-place` key as third argument, while the original implementation of `sort` only accepted two arguments, which is not necessary. The sorting is done in place anyhow. This commit modifies the `denote-sequence--get-largest` function to be compatible with older Emacs versions.
=> Use older-compatible `sort` call in `denote-sequence--get-largest`

denote-sort.el
The function `denote-sort-dired` wasn't working due to the `identifier` missing case in `denote-sort-files`. This is useful when you customize `denote-file-name-components-order`.
=> Add identifier comparison sort function in denote-sort-files

denote-sequence.el
This patch fixes the regression bug in
`denote-sequence-get-all-files`, as discussed in #526. The core idea behind this fix is to delete duplicates within the list of files and buffers in the `denote-directory` matching a certain signature.
=> Fix the regression bug discussed in #526

denote.el
I have added `denote-current-title` so that the non-sluggified title
is accessible in `denote-after-new-note-hook` and
`denote-after-rename-file-hook`. This can be useful to those with
a custom front matter (not the default one).
This is not needed for other components because they appear identical
in the file name and the front matter and so they can be retrieved
from the file name.
I will give examples in #532 and #521.
=> New denote-current-title variable

denote-sequence.el
Hi Prot,
This pull request fixes what I believe to be a bug involving the 'denote-sequence' command.
When I have at least 10 top-level sequence notes in my 'denote-directory' and call 'denote-sequence' to create a new child for the parent with sequence "1", the actual parent ends up being that with sequence "10" if there are exactly ten top-level sequence notes, "12" if there are 12, "100" if there are 100, etc.
This all comes down to 'denote-sequence-get-all-sequences-with-prefix' using 'string-match-p' to test for matches. I think it should instead match the components individually.
This is all with the latest main. If there are other branches that I don't know about which address this, apologies!
Thanks!
=> Fix false matches in 'denote-sequence-get-all-sequences-with-prefix'

denote-sequence.el, tests/denote-test.el
This adds tests as mentioned in pull request #540. It also fixes similar false matches in 'denote-sequence-get-all-files-with-prefix'.
The latter function is apparently mainly used by 'denote-sequence-find-dired', and in the process of trying that command out, I found a number of bugs involvings its use of ''denote-sequence-get-relative' --- which I fix here as well.
=> Add tests for false matches addressed by pull request #540 and fix related issues

denote.el
Hi, this preserves the inner extension when renaming encrypted files again (#172).
=> Use denote-get-file-extension in denote--rename-file

denote.el
This is following the discussion [here](https://github.com/protesilaos/denote/issues/550#issuecomment-2693343371) where we decided to take a step back about the renaming of notes inside an org-capture buffer because it causes issues.
I reverted the relevant commits.
Issue #550 may still not be resolved, but I cannot reproduce it.
=> Revert commits about renaming org-capture buffers

denote.el
This fixes a problem with opening links to encrypted `org` files.
For example, if the target file has been exported with the same name, the following error occurs:
```
denote-link-ol-follow: Wrong type argument: stringp, nil
```
=> Respect encryption-file-extensions in get-path-by-id

denote.el
Links with location identifiers like `denote:20240611T111809::/apple/` are currently treated as query links.
This fixes the opening of these links and makes them use the correct face.
=> Fix Org links with location identifiers

denote.el
This documents that `denote-file-name-components-order` should probably not be used in custom code.
=> Add info in docstring of denote-file-name-components-order

README.org, denote.el
- I changed the order of the `or` subexpressions in `denote-date-prompt`. It was probably unintended.
- I changed the default value of `denote-use-keywords` to the `default` symbol, because `nil` (ie the empty list) is a valid value for keywords.
=> Small fixes

denote.el
On Windows, given the `link` as an identifer `"20250312T161853"` , the result of `(denote-link--ol-resolve-link-to-target 
link)` is a Windows path `"c:/path/to/the/file.extension"`
However, the result of `(file-exists-p (string-trim-right match ":.*"))` is `nil`, because `(string-trim-right "c:/path/to/the/file.extension" ":.*")` returns `"c"` ,which is the driver letter on Windows.
We can fix it by this: `(string-trim-right "c:/path/to/the/file.extension" ":[^/]+.*")`
https://github.com/protesilaos/denote/issues/577
=> Fix Windows compatibility of `denote-link-ol-follow`

README.org
When using `denote-use-template`with `let` binding, it is advisable to set `denote-org-capture-specifiers` to nil or an empty string.
This fixes #545.
=> Add note about denote-use-template duplicate

denote.el
It does not appear to be used in the code and it is probably better to configure `denote-link-description-format` to include the date in the link description.
I can provide an example if you want!
=> Remove include-date parameter from linking functions

README.org, denote.el
The signature in the front matter was always sluggified according to `denote-sluggify-signature` rather than the function specified in `denote-file-name-slug-function`. I fix this here.
I also renamed the function `denote-sluggify` to `denote-sluggify-and-apply-rules` to make it clear that 2 distinct ideas are involved.
=> Ensure sluggification of signature in front matter obey denote-file-name-slug-functions

README.org, denote.el, tests/denote-test.el
Hello Prot,
In this pull request, I make the date and identifier independent at
the core. The default is still unchanged, ie the identifier is derived
from the date.
There is a new identifier prompt. For now, the format of the string
should be the one we know (20240101T010101). Users do not need to use
this new prompt, though it is there.
Most users should not notice much changes. The only thing is that
users that have started to modify their identifiers should probably
now use `denote-rename-file-identifier` instead of
`denote-rename-file-date`. The latter would only change the date in
the front matter (as the date component is technically not in the file
name anymore).
Also, the date and identifier in the front matter may not always be
the same, which is probably a good thing, in fact. …
=> Make the date and identifiers independent and new identifier prompt

denote.el
This fixes #616.
Later, I will also make the other change I mentioned about `denote-get-backlinks`. I will probably just remove `denote-retrieve-filename-identifier-with-error` completely. This can be done later.
On an unrelated note, I think commit 9549d97 should be reverted. The functions `denote-generate-identifier-as-{date/number}` are not user commands and they are also not meant to be called from lisp directly. Even `denote-get-identifier-function` should probably not be used in packages. They are example identifier generation functions and users have to make a function with 2 parameters if they create their own.
=> Fix denote--rename-file for files without an identifier

denote.el
Hello Prot!
In this pull request, I made the final changes to allow custom
identifier formats.
For your info (and anyone interested), the challenge was to find the
backlinks correctly. I needed to be able to retrieve links according
to the format of each supported file type. For example, for org, I
need to look for "[denote:some-identifier]" instead of only
"some-identifier". This is because if an id is "11", we cannot just
look for "11". We also cannot just look for "denote:11" because it
will also match "denote:11111".
I did the requisite changes. In fact, I also created the function
`denote--get-all-backlinks` that may be useful eventually. Right now,
each call to `denote-backlinks` reads all notes. With
`denote--get-all-backlinks`, we scan all files once and we have ALL
backlinks, for …
=> Custom identifier formats

denote.el
These are small cleanups following my last pull request. With these
changes, identifiers are now completely optional and arbitrary, like
other file name components.
The default is `nil`. The use-case I have in mind is the one in your
wishlist in the manual. Say a user decide to configure their
identifier format to be "20250101W000000" on a Wednesday and
"20250102T000000" on a Thursday. It may look odd if notes on Thursdays
lack the identifier delimiter. With this new user option, the
delimiter can be made always present.
All file name components can now be sluggified.
This makes it so `denote-directory-files` may include notes that
respect Denote's file naming scheme, but do not have an identifier.
Packages will have to decide whether it makes sense to include them or
not.
I have adjusted …
=> Various adjustments

README.org
Hello Prot!
I have updated the manual to be more precise about the file-naming
scheme and to make it acknowledge the latest development about
identifiers.
While reviewing the manual, I thought it seemed strange that an
example file produced by Denote is not shown until after all creation
and renaming commands are explained. So I added a couple lines in the
Overview section.
This would close #586 for me. Let me know if you want to include a
section in the manual about custom identifier formats or you prefer
keeping it on GitHub as documentation. I am fine with either.
Also, in case you missed it, I also replied to your question
[here](https://github.com/protesilaos/denote/commit/947f0be070c686f2b253498d6eb65ac2abcaee8e).
=> Various precisions in the manual
